package jcd;

import bo.Salesperson;
import dao.SalespersonHandler;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.GlobalData;

/**
 * Swing form for the salesperson list
 */
public class FrmListSalespeople extends javax.swing.JInternalFrame {

    // The SalespersonHandler we'll be using a lot
    SalespersonHandler sph = new SalespersonHandler();
    
    /** Creates new form FrmListSalespeople */
    public FrmListSalespeople() {
        initComponents();
        populateSalespeople();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalespeople = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnReload = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnDelete = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnEdit = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Staff List");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblSalespeople.setAutoCreateRowSorter(true);
        tblSalespeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSalespeople.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSalespeople);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(576, 34));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(filler4);

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        jPanel5.add(btnReload);
        jPanel5.add(filler1);

        btnDelete.setText("Delete...");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete);
        jPanel5.add(filler2);

        btnEdit.setText("Edit...");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel5.add(btnEdit);
        jPanel5.add(filler3);

        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        populateSalespeople();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Get the index of the selected row
        int selectedRow = tblSalespeople.getSelectedRow();

        // If a row is actually selected (that is, not -1)
        if (selectedRow != -1) {

            // Get the ID number from the first column (0) of the selected row
            int id = (int)tblSalespeople.getValueAt(selectedRow, 0);

            Salesperson sp = sph.findSalesperson(id);

            if (sp != null) {
                DlgUpdateSalesperson dlg = new DlgUpdateSalesperson(null, true);
                dlg.setSalesperson(sp);
                dlg.setVisible(true);
                if (dlg.getReturnStatus() == DlgUpdateSalesperson.RET_OK) {
                    this.populateSalespeople();
                }
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Get the index of the selected row
        int selectedRow = tblSalespeople.getSelectedRow();

        // If a row is actually selected (that is, not -1)
        if (selectedRow != -1) {

            // Get the ID number from the first column (0) of the selected row
            int id = (int)tblSalespeople.getValueAt(selectedRow, 0);

            // Don't allow deletion if selected salesperson is logged in
            if (GlobalData.getSalesperson().getId() == id) {
                JOptionPane.showMessageDialog(this,
                        "Cannot delete logged-in salesperson.");
                return;
            }
            
            // Show a dialog and put the result in res
            int res = JOptionPane.showConfirmDialog(this,
                String.format("Are you sure you want to delete the salesperson with ID %d? This will delete all their sales.", id));

            // If the user clicked OK
            if (res == JOptionPane.OK_OPTION) {
                // Delete the selected salesperson
                sph.deleteSalesperson(id);

                // Reload the list
                populateSalespeople();
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "Please select a salesperson to delete.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        populateSalespeople();
    }//GEN-LAST:event_formInternalFrameOpened

    /**
     * Fill the salesperson table (tblSalespersons) with all the Salesperson relations in the database
     */
    public void populateSalespeople() {

        // Use the SalespersonHandler to return a list of salespeople from the database as
        // Salesperson objects
        List<Salesperson> sps = sph.getSalespeople();

        // Magic DefaultTableModel code for working with Swing JTable objects
        // (no need to understand; just copy and paste)
        String[] columns = new String[] { "ID", "Username", "Name", "Phone", "Email" };
        DefaultTableModel tblModel = new DefaultTableModel(columns, 0) {
            // Make sure none of the cells is editable
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        sps.forEach((sp)->{
            // For each row from the database, add it to the salesperson table
            tblModel.addRow(sp.getRow());
        });
        tblSalespeople.setModel(tblModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReload;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalespeople;
    // End of variables declaration//GEN-END:variables

}
