package jcd;

import java.beans.PropertyVetoException;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import utils.GlobalData;

/**
 * Swing form for the main window containing all the other windows
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */

    // Create instances of each form we will need (e.g. login form, car list
    // form, etc.)
    // NOTE: This will not show the forms yet
    private FrmLogin frmLogin = new FrmLogin();
    private FrmListCars frmListCars = new FrmListCars();
    private FrmSellCar frmSellCar = new FrmSellCar();
    private FrmAddCar frmAddCar = new FrmAddCar();

    /**
     * Hashmap containing all the forms we'll be using. Key is a string
     * containing the name of the form, value is the form object as instantiated
     * above.
     */
    private Map<String, JInternalFrame> forms = new HashMap<>();
    
    public FrmMain() {
        // Basic Swing stuff
        initComponents();

        // Give a name to each form and add it to our hashmap
        forms.put("frmLogin", frmLogin);
        forms.put("frmListCars", frmListCars);
        forms.put("frmSellCar", frmSellCar);
        forms.put("frmAddCar", frmAddCar);
        
        // For each form we created, add it to the form container in the main
        // window (NOTE: This still won't show the forms yet)
        forms.values().forEach((frm)->{
            jdpContainer.add(frm);
        });
    }
    
    /**
     * Show a form without first checking if a Salesperson is logged in
     * @param name The name of the form
     */
    private void showForm(String name) {
        showForm(name, false);
    }
    
    /**
     * Show a named form, checking whether a Salesperson is logged in if desired
     * 
     * @param name The name of the form
     * @param checkLogin Whether to check if a Salesperson is logged in
     */
    private void showForm(String name, boolean checkLogin) {

        // If the global variable sp (Salesperson) is null, nobody is logged in
        if (checkLogin && GlobalData.sp == null) {
            // Do not pass go, do not collect $200--show the login form
            showForm("frmLogin", false);

        // We're here because either we're not checking for a login OR
        // sp != null (we're actually logged in)
        } else {
            // Get the form from our map of forms based on the given name
            JInternalFrame form = forms.get(name);

            // If the form exists but had been closed at some point, we have to
            // recreate it
            if (form != null && form.isClosed()) {
                try {
                    // Get the class of the closed form and make a new instance
                    form = forms.get(name).getClass().getDeclaredConstructor().newInstance();

                    // Replace the closed form in our map with the new one
                    forms.put(name, form);

                    // Add the new form to our main window
                    jdpContainer.add(form);
                } catch (InstantiationException | IllegalAccessException |
                        NoSuchMethodException | SecurityException |
                        IllegalArgumentException |
                        InvocationTargetException ex) {
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            // Some way or another we have the form we need--make it visible
            // (NOTE: This finally shows the form)
            form.setVisible(true);

            try {
                // Try to select the form (bring it to the front)
                form.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniLogIn = new javax.swing.JMenuItem();
        mniLogOut = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mniCut = new javax.swing.JMenuItem();
        mniCopy = new javax.swing.JMenuItem();
        mniPaste = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mnuCars = new javax.swing.JMenu();
        mniListCars = new javax.swing.JMenuItem();
        mniAddCar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        javax.swing.GroupLayout jdpContainerLayout = new javax.swing.GroupLayout(jdpContainer);
        jdpContainer.setLayout(jdpContainerLayout);
        jdpContainerLayout.setHorizontalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jdpContainerLayout.setVerticalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        getContentPane().add(jdpContainer, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");

        mniLogIn.setText("Log In…");
        mniLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogInActionPerformed(evt);
            }
        });
        mnuFile.add(mniLogIn);

        mniLogOut.setText("Log Out…");
        mnuFile.add(mniLogOut);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edit");

        mniCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.META_DOWN_MASK));
        mniCut.setText("Cut");
        mnuEdit.add(mniCut);

        mniCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.META_DOWN_MASK));
        mniCopy.setText("Copy");
        mnuEdit.add(mniCopy);

        mniPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.META_DOWN_MASK));
        mniPaste.setText("Paste");
        mnuEdit.add(mniPaste);

        jMenuBar1.add(mnuEdit);

        mnuManage.setText("Manage");

        mnuCars.setText("Cars");

        mniListCars.setText("List…");
        mniListCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListCarsActionPerformed(evt);
            }
        });
        mnuCars.add(mniListCars);

        mniAddCar.setText("Add Car...");
        mniAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCarActionPerformed(evt);
            }
        });
        mnuCars.add(mniAddCar);

        mnuManage.add(mnuCars);

        jMenuBar1.add(mnuManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Called when the "List Cars" menu item is clicked
    private void mniListCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListCarsActionPerformed
        showForm("frmListCars", true);
    }//GEN-LAST:event_mniListCarsActionPerformed

    // Called when the "Log In" menu item is clicked
    private void mniLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogInActionPerformed
        showForm("frmLogin", false);
    }//GEN-LAST:event_mniLogInActionPerformed

    // Called when the "Add Car" menu item is clicked
    private void mniAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCarActionPerformed
        showForm("frmAddCar", true);
    }//GEN-LAST:event_mniAddCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpContainer;
    private javax.swing.JMenuItem mniAddCar;
    private javax.swing.JMenuItem mniCopy;
    private javax.swing.JMenuItem mniCut;
    private javax.swing.JMenuItem mniListCars;
    private javax.swing.JMenuItem mniLogIn;
    private javax.swing.JMenuItem mniLogOut;
    private javax.swing.JMenuItem mniPaste;
    private javax.swing.JMenu mnuCars;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuManage;
    // End of variables declaration//GEN-END:variables
}
